 development:
   dialect: mysql
   datasource: ${MYSQL_ROOT_USER}:${MYSQL_ROOT_PASSWORD}@tcp(127.0.0.1)/freeeeren?parseTime=true
   dir: ./migrations/ 
 staging:
   dialect: mysql
   datasource: ${MYSQL_ROOT_USER}:${MYSQL_ROOT_PASSWORD}@tcp(127.0.0.1)/freeeeren?parseTime=true
   dir: ./migrations/
