 version: "3"
 services:
   db:
     image: mysql:5.7
     ports:
       - ${LOCAL_MYSQL_PORT}:3306
     environment:
       MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
