 version: "3"
 services:
 
   mysql:
     image: mysql:latest
     ports:
       - ${LOCAL_MYSQL_PORT}:3306
     environment:
       MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     volumes:
       - ./script:/docker-entrypoint-initdb.d 
